sonar.projectKey=com.sranker.shoppinglistmanager
sonar.projectName=ShoppingListManager
sonar.projectVersion=1.0

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/R.class, **/BuildConfig.*, **/Manifest*.*, **/*Test*.*, android/**/*.*, **/*_Hilt*, **/*Hilt*, **/di/**, **/*_Factory*, **/*_MembersInjector*, **/*_ViewBinding*, **/Dagger*.*
